/*!
* tMind-Cli v1.0.0
* (c) 2021-2022  Smpoo soft Co. Shanghai China
* Released under the MIT License.
* Author: David
* CreateDate: 2021-03-05
* LastBuild: 2021-03-19 00:41:38
*/
!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?e(exports):"function"==typeof define&&define.amd?define(["exports"],e):e((t="undefined"!=typeof globalThis?globalThis:t||self).tmind={})}(this,(function(t){"use strict";const e=(t,e=2)=>`${t}`.padStart(e,"0"),n=function(t,n){const s=(t=>{const n=`${t.getFullYear()}`;return{yyyy:n,yy:e(n.slice(-2)),mm:e(t.getMonth()+1),dd:e(t.getDate()),hh:e(t.getHours()),mi:e(t.getMinutes()),ss:e(t.getSeconds()),ms:e(t.getMilliseconds(),3)}})(t);return(n||"yyyy-mm-dd").replace(/yyyy|yy|dd|hh|mi|ms|ss|mm/g,(t=>Array.isArray(t)?"":s[t]||""))},s=t=>{if("Invalid Date"===t.toString())throw new Error("Get invalid param for fuction tdate. This parma can be null/undefind or datetime string, also can be number just < 8640000000000000");return new o(t)};class o{constructor(t){this.toCode=t=>n.call(this,this.val,"yyyymmddhhmissms"),this.format=t=>n.call(this,this.val,t||"yyyy-mm-dd"),this.formatCn=()=>"",this.formatLunar=(t=!0)=>{const e=Intl.DateTimeFormat("zh-u-ca-chinese-nu-latn").format(this.val);return t?e.split("年")[1]||"":e},this.formatBh=()=>Intl.DateTimeFormat("zh-chinese-u-ca-buddhist").format(this.val).replace(/-/,"年").replace(/-/,"月"),this.formatWorld=t=>Intl.DateTimeFormat(t||"fr-ca").format(this.val),this.val=t}}const a=["[30m","[39m"],i=["[34m","[39m"],r=["[32m","[39m"],m=["[33m","[39m"],l=["[31m","[39m"],c=["[44m","[49m"],d=["[104m","[49m"],u=["[42;32m","[49m"],f=["[102m","[49m"],h=["[43;30m","[49m"],y=["[103m","[49m"],p=["[41m","[49m"],g=["[105m","[49m"],$={INFO:["信息",c[0],c[1],i[0],i[1]],SUCC:["成功",u[0],u[1],r[0],r[1]],WARN:["警告",h[0],h[1],m[0],m[1]],ERR:["错误",p[0],p[1],l[0],l[1]]},w={INFO:["信息",d[0],d[1],a[0],a[1]],SUCC:["成功",f[0],f[1],r[0],r[1]],WARN:["警告",y[0],y[1],a[0],a[1]],ERR:["错误",g[0],g[1],l[0],l[1]]},b={INFO:console.log,SUCC:console.log,WARN:console.warn,ERR:console.error};t.Tmind=class{constructor(){this.name="This is a class"}},t.echo=function(t,e,n){const s=`${n}`.toUpperCase(),o=n&&b[s]||b.INFO;if("function"==typeof o)if(globalThis.window){const[n,a,i,r,m]=w[s]||["","","","",""];o(`${a} ${e||n} ${i} ${r} ${t} ${m}`)}else{const[n,a,i,r,m]=$[s]||["","","","",""];o(`${a} ${e||n} ${i} ${r} ${t} ${m}`)}},t.tdate=function(t){switch(typeof t){case"string":case"number":return s(new Date(t));case"undefined":return new o(new Date);default:if(Array.isArray(t)){const[e,n,...o]=t;return s(new Date(e,n,...o))}return null===t?new o(new Date):s(new Date("invalid"))}},Object.defineProperty(t,"__esModule",{value:!0})}));
