/*!
* tMind-Cli v1.0.0
* (c) 2021-2022  Smpoo soft Co. Shanghai China
* Released under the MIT License.
* Author: David
* CreateDate: 2021-03-05
* LastBuild: 2021-03-18 09:12:27
*/
!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?e(exports):"function"==typeof define&&define.amd?define(["exports"],e):e((t="undefined"!=typeof globalThis?globalThis:t||self)["tmind-core"]={})}(this,(function(t){"use strict";const e=(t,e=2)=>`${t}`.padStart(e,"0"),n=function(t,n){const s=(t=>{const n=`${t.getFullYear()}`;return{yyyy:n,yy:e(n.slice(-2)),mm:e(t.getMonth()+1),dd:e(t.getDate()),hh:e(t.getHours()),mi:e(t.getMinutes()),ss:e(t.getSeconds()),ms:e(t.getMilliseconds(),3)}})(t);return(n||"yyyy-mm-dd").replace(/yyyy|yy|dd|hh|mi|ms|ss|mm/g,(t=>Array.isArray(t)?"":s[t]||""))},s=t=>{if("Invalid Date"===t.toString())throw new Error("Get invalid param for fuction tdate. This parma can be null/undefind or datetime string, also can be number just < 8640000000000000");return new o(t)};class o{constructor(t){this.toCode=t=>n.call(this,this.val,"yyyymmddhhmissms"),this.format=t=>n.call(this,this.val,t||"yyyy-mm-dd"),this.formatCn=()=>"",this.formatLunar=(t=!0)=>{const e=Intl.DateTimeFormat("zh-u-ca-chinese-nu-latn").format(this.val);return t?e.split("年")[1]||"":e},this.formatBh=()=>Intl.DateTimeFormat("zh-chinese-u-ca-buddhist").format(this.val).replace(/-/,"年").replace(/-/,"月"),this.formatWorld=t=>Intl.DateTimeFormat(t||"fr-ca").format(this.val),this.val=t}}const r=["[34m","[39m"],a=["[32m","[39m"],i=["[33m","[39m"],m=["[31m","[39m"],c=["[44m","[49m"],l=["[42;30m","[49m"],d=["[43;30m","[49m"],u=["[41m","[49m"],f={INFO:["信息",c[0],c[1],r[0],r[1]],SUCC:["成功",l[0],l[1],a[0],a[1]],WARN:["警告",d[0],d[1],i[0],i[1]],ERR:["错误",u[0],u[1],m[0],m[1]]},h={INFO:["信息",c[0],c[1],r[0],r[1]],SUCC:["成功",l[0],l[1],a[0],a[1]],WARN:["警告",d[0],d[1],i[0],i[1]],ERR:["错误",u[0],u[1],m[0],m[1]]},y={INFO:console.log,SUCC:console.log,WARN:console.warn,ERR:console.error};t.Tmind=class{constructor(){this.name="This is a class"}},t.echo=function(t,e="",n="INFO"){const s=n&&y[`${n}`.toUpperCase()]||y.INFO;if("function"==typeof s)if(window){const[o,r,a,i,m]=h[n]||["","","","",""];s(`${r} ${e||o} ${a} ${i} ${t} ${m}`)}else{const[o,r,a,i,m]=f[n]||["","","","",""];s(`${r} ${e||o} ${a} ${i} ${t} ${m}`)}},t.tdate=function(t){switch(typeof t){case"string":case"number":return s(new Date(t));case"undefined":return new o(new Date);default:if(Array.isArray(t)){const[e,n,...o]=t;return s(new Date(e,n,...o))}return null===t?new o(new Date):s(new Date("invalid"))}},Object.defineProperty(t,"__esModule",{value:!0})}));
