/*!
* tMind-Cli v1.0.0
* (c) 2021-2022  Smpoo soft Co. Shanghai China
* Released under the MIT License.
* Author: David
* CreateDate: 2021-03-05
* LastBuild: 2021-03-18 08:52:26
*/
const t=(t,e=2)=>`${t}`.padStart(e,"0"),e=function(e,n){const a=(e=>{const n=`${e.getFullYear()}`;return{yyyy:n,yy:t(n.slice(-2)),mm:t(e.getMonth()+1),dd:t(e.getDate()),hh:t(e.getHours()),mi:t(e.getMinutes()),ss:t(e.getSeconds()),ms:t(e.getMilliseconds(),3)}})(e);return(n||"yyyy-mm-dd").replace(/yyyy|yy|dd|hh|mi|ms|ss|mm/g,(t=>Array.isArray(t)?"":a[t]||""))},n=t=>{if("Invalid Date"===t.toString())throw new Error("Get invalid param for fuction tdate. This parma can be null/undefind or datetime string, also can be number just < 8640000000000000");return new a(t)};class a{constructor(t){this.toCode=t=>e.call(this,this.val,"yyyymmddhhmissms"),this.format=t=>e.call(this,this.val,t||"yyyy-mm-dd"),this.formatCn=()=>"",this.formatLunar=(t=!0)=>{const e=Intl.DateTimeFormat("zh-u-ca-chinese-nu-latn").format(this.val);return t?e.split("年")[1]||"":e},this.formatBh=()=>Intl.DateTimeFormat("zh-chinese-u-ca-buddhist").format(this.val).replace(/-/,"年").replace(/-/,"月"),this.formatWorld=t=>Intl.DateTimeFormat(t||"fr-ca").format(this.val),this.val=t}}const s=["[34m","[39m"],r=["[32m","[39m"],o=["[33m","[39m"],i=["[31m","[39m"],m=["[44m","[49m"],c=["[42;30m","[49m"],l=["[43;30m","[49m"],h=["[41m","[49m"],u={INFO:["信息",m[0],m[1],s[0],s[1]],SUCC:["成功",c[0],c[1],r[0],r[1]],WARN:["警告",l[0],l[1],o[0],o[1]],ERR:["错误",h[0],h[1],i[0],i[1]]},d={INFO:["信息",m[0],m[1],s[0],s[1]],SUCC:["成功",c[0],c[1],r[0],r[1]],WARN:["警告",l[0],l[1],o[0],o[1]],ERR:["错误",h[0],h[1],i[0],i[1]]},y={INFO:console.log,SUCC:console.log,WARN:console.warn,ERR:console.error};var f={Tmind:class{constructor(){this.name="This is a class"}},tdate:function(t){switch(typeof t){case"string":case"number":return n(new Date(t));case"undefined":return new a(new Date);default:if(Array.isArray(t)){const[e,a,...s]=t;return n(new Date(e,a,...s))}return null===t?new a(new Date):n(new Date("invalid"))}},echo:function(t,e="",n="INFO"){const a=n&&y[n]||y.INFO;if("function"==typeof a)if(window){const[s,r,o,i,m]=d[n]||["","","","",""];a(`${r} ${e||s} ${o} ${i} ${t} ${m}`)}else{const[s,r,o,i,m]=u[n]||["","","","",""];a(`${r} ${e||s} ${o} ${i} ${t} ${m}`)}}};export default f;
