export declare class Tdate {
    private val;
    constructor(initVal: Date);
    get isLeap(): boolean;
    get abs(): number;
    get year(): number;
    get month(): number;
    get day(): number;
    get hour(): number;
    get minute(): number;
    get second(): number;
    get millisecond(): number;
    get week(): number;
    get quarter(): number;
    get solar(): string;
    get sign(): string;
    get animal(): string;
    get indexOfQuarter(): number;
    get indexOfYear(): number;
    get daysOfMonth(): number;
    get daysOfQuarter(): number;
    get daysOfYear(): number;
    get ratioOfWeek(): number;
    get ratioOfMonth(): number;
    get ratioOfQuarter(): number;
    get ratioOfYear(): number;
    get tiangan(): string;
    get weekOfMonth(): number;
    get weekOfYear(): number;
    format: (fmt?: string | undefined) => string;
    formatAsCn: (withYear?: boolean, withTime?: boolean | undefined) => string;
    formatAsLunar: (skipYear?: boolLike) => string;
    formatAsBh: () => string;
    formatAsWorld: (languageTag: string | null | undefined) => string;
    getWeek: (local?: "zh" | "en" | undefined) => string | number;
    getWeekOfMonth: (local?: "zh" | "en" | undefined) => string | number;
    getWeekOfYear: (local?: "zh" | "en" | undefined) => string | number;
    getQuarter: (local?: "zh" | "en" | undefined) => string | number;
    getOffset: (diffNum: number, diffType?: "year" | "month" | "day" | "week" | undefined) => string;
    getDiff: (dateVal: Date | Tdate | string | number, outputType?: "ms" | "year" | "month" | "day" | "second" | "minute" | "hour" | "week" | undefined) => number;
    toNumber: (notTimestamp?: boolean, fmt?: string | undefined) => number;
    toJson: (local?: "zh" | "en" | undefined) => IObj<number | boolean | string>;
    toArr: (includTime?: boolean | undefined) => number[];
}
export declare function tdate(): Tdate;
export declare function tdate(val: string): Tdate;
export declare function tdate(val: number): Tdate;
export declare function tdate(y: number, m: number, d?: number | undefined, h?: number | undefined, mi?: number | undefined, s?: number | undefined, ms?: number | undefined): Tdate;
export declare function tdate(val: null): Tdate;
